apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  type: LoadBalancer        # Changed from NodePort to LoadBalancer for AWS EKS
  selector:
    app: ml-model
  ports:
    - protocol: TCP
      port: 80              # External port exposed by the Load Balancer
      targetPort: 5000      # Port your app listens on inside container
