name: Trigger Training on CSV Upload

on:
  push:
    paths:
      - '**/*.csv'

jobs:
  train-on-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training
        run: |
          python scripts/train_model.py

      - name: Generate model report
        run:
          python scripts/generate_report.py

